# Generated by Django 5.1.1 on 2024-10-03 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0002_habitacion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('ventanas', models.IntegerField()),
                ('camas', models.CharField(max_length=100)),
                ('numero_de_camas', models.IntegerField()),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('jacuzzi', models.BooleanField(default=False)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.habitacion')),
            ],
        ),
    ]
