# Generated by Django 5.1.1 on 2024-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0005_rename_disponiblidad_servicios_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallehabitacion',
            name='Numero_de_habitacion',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallehabitacion',
            name='habitaciones_disponibles',
            field=models.IntegerField(default=1),
        ),
    ]
