# Generated by Django 5.1.1 on 2024-11-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0008_remove_detallehabitacion_habitaciones_disponibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
