# Generated by Django 5.1.1 on 2024-11-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0009_habitacion_slug_servicios_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='public_id_img',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicios',
            name='public_id_img',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
