# Generated by Django 5.1.1 on 2024-10-16 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HotelApp', '0008_remove_detallehabitacion_habitaciones_disponibles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_reserva', models.TimeField()),
                ('fecha_final_reserva', models.TimeField()),
                ('estado', models.CharField(max_length=50)),
                ('Numero_de_habitacion', models.IntegerField(unique=True)),
                ('costo', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitacionesReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personas', models.IntegerField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.habitacion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.servicios')),
            ],
        ),
    ]
