# Generated by Django 5.1.1 on 2024-10-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_final_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_inicio_reserva',
        ),
    ]
