# Generated by Django 5.1.1 on 2024-10-15 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0007_servicios_precio'),
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitacionesReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personas', models.IntegerField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.habitacion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosReservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.servicios')),
            ],
        ),
    ]
