# Generated by Django 5.1.1 on 2024-10-16 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0002_remove_reserva_fecha_final_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_final_reserva',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_inicio_reserva',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
