# Generated by Django 5.1.1 on 2024-10-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0002_habitacionesreservas_serviciosreservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='Numero_de_habitacion',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
