# Generated by Django 5.1.1 on 2024-10-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0003_reserva_fecha_final_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Numero_de_habitacion',
            field=models.IntegerField(),
        ),
    ]
