# Generated by Django 5.1.1 on 2024-10-27 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0004_alter_reserva_numero_de_habitacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(max_length=255)),
                ('reseña', models.IntegerField()),
                ('habitacion_reservada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.habitacionesreservas')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
