# Generated by Django 5.1.1 on 2024-12-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0007_alter_pago_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='firebase_token',
            field=models.CharField(default='', help_text='Token FCM del cliente', max_length=255),
        ),
    ]
